source 'https://rubygems.org'
ruby '2.2.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  gem 'faker'
  gem 'factory_girl_rails'
  gem 'database_cleaner'

  gem 'rspec-rails'

  gem 'airborne'
  gem 'shoulda-matchers'
  gem 'shoulda-callback-matchers', '~> 1.0'
  gem 'webmock'

  gem 'guard'
  gem 'guard-rails'
  gem 'guard-bundler'
  gem 'guard-rubocop'
  gem 'guard-rspec'

  gem 'spring-commands-rspec'
  gem 'did_you_mean'
  gem 'rubocop', require: false
  gem 'pry-rails'
  gem 'shog'
  gem 'better_errors'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'meta_request'
  gem 'guard-livereload', require: false
  gem 'letter_opener'
  gem 'rerun'
end

##
# ------------------------------
# FRONT END
# ------------------------------
# template generator
gem 'slim-rails'

# twitter bootstrap
gem 'bootstrap-sass'

# Jquery UI
gem 'jquery-ui-rails'

# auto prefixer
gem 'autoprefixer-rails'

# bower dependencies manager for rails
gem 'bower-rails'

# modernizr
gem 'modernizr-rails', '~> 2.7.1'

# font awesome
gem 'font-awesome-rails'

# Noty JS library
gem 'noty-rails'

##
# ------------------------------
# AUTHENTICATION AND AUTHORIZATION
# ------------------------------
# Flexible authentication solution for Rails with Warden
gem 'devise'

# Send Devise's emails in background
gem 'devise-async'

##
# ------------------------------
# API
# ------------------------------
gem 'grape'
gem 'grape-entity'
gem 'grape-apiary'
gem 'grape-swagger'
gem 'grape-rails-cache'

##
# ------------------------------
# OTHERS
# ------------------------------
# Load environment variables from .env file
gem 'dotenv-rails'
